config/routes.rb
MassageApi::Application.routes.draw do
  namespace :api do
    resources :matchings do
      collection do
        post 'reservation'
        post 'cancellation'
        get  'reservation_list'
      end
    end

    resources :stores do
      collection do
        post 'edit'
        get  'search'
      end
    end

    resources :customers do
      collection do
        post 'edit'
      end
    end

    resources :users do
      collection do
        post 'register'
        post 'login'
      end
    end
  end

  resources :matchings, only: [:index, :show]

  resources :stores, only: [:index, :show]

  resources :customers, only: [:index, :show]

  resources :users, only: [:index, :show]

end

app/models/customer.rb
class Customer < ActiveRecord::Base
end

app/models/matching.rb
class Matching < ActiveRecord::Base
end

app/models/store.rb
class Store < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/api/api_base_controller.rb
class Api::ApiBaseController < ApplicationController
end

app/controllers/api/customers_controller.rb
class Api::CustomersController < Api::ApiBaseController
  def edit
    user  = User.find_by(user_id: params[:user_id])
    customer = Customer.find_by(user_id: user.id)

    customer_params = ActionController::Parameters.new(params).permit(:user_id, :name, :mail_address, :memo)
    edit_params  = customer_params.merge(user_id: user.id)

    if customer.present?
      customer.update(edit_params)
    else
      customer = Customer.new(edit_params).save!
    end
    result = 'true'
  rescue => e
    p ">>>>>>>>>>> error! : #{e}"
    Rails.logger.error ">>>>>>>>>>> error! : #{e}"
    result = 'false'
  ensure
    render json: {result: result}
  end
end

app/controllers/api/matchings_controller.rb
class Api::MatchingsController < Api::ApiBaseController
  def reservation
    matching_params = ActionController::Parameters.new(params).permit(:customer_id, :store_id)

    if Matching.find_by(customer_id: matching_params[:customer_id], store_id: matching_params[:store_id], enable_flg: 1).present?
      result  = 'false'
      message = '既に予約済です'
    else
      Matching.new(matching_params.merge({enable_flg: 1})).save!
      result  = 'true'
      message = '予約に成功しました'
    end
  rescue => e
    p ">>>>>>>>>>> error! : #{e}"
    Rails.logger.error ">>>>>>>>>>> error! : #{e}"
    result  = 'false'
    message = '予約に失敗しました'
  ensure
    render json: { result: result, message: message }
  end

  def cancellation
    matching = Matching.find_by(id: params[:id])

    matching.update(enable_flg: 0)
    result  = 'true'
    message = '予約を取り消しました'
  rescue => e
    p ">>>>>>>>>>> error! : #{e}"
    Rails.logger.error ">>>>>>>>>>> error! : #{e}"
    result  = 'false'
    message = '予約の取り消しに失敗しました'
  ensure
    render json: { result: result, message: message }
  end

  def reservation_list
    mt = Matching.arel_table

    case params[:user_type]
    when '0'
      st = Store.arel_table

      condition = mt[:customer_id].eq(params[:user_id])
      join_conditions = mt.join(st).on(st[:id].eq(mt[:store_id])).join_sources
      select_columns = ['*', 'stores.name as name']
    when '1'
      ct = Customer.arel_table

      condition = mt[:store_id].eq(params[:user_id])
      join_conditions = mt.join(ct).on(ct[:id].eq(mt[:customer_id])).join_sources
      select_columns = ['*', 'customers.name as name']
    end

    matchings = Matching.select(*select_columns).where(condition.and(mt[:enable_flg].eq(1))).joins(join_conditions).order(mt[:id].desc)

    ret_data = matchings.map{ |matching| { name: matching.name } }
  rescue => e
    p ">>>>>>>>>>> error! : #{e}"
    Rails.logger.error ">>>>>>>>>>> error! : #{e}"
    ret_data = []
  ensure
    render json: { result: ret_data }
  end
end

app/controllers/api/stores_controller.rb
class Api::StoresController < Api::ApiBaseController
  def edit
    user  = User.find_by(user_id: params[:user_id])
    store = Store.find_by(user_id: user.id)

    store_params = ActionController::Parameters.new(params).permit(:user_id, :name, :address, :geo_data, :mail_address, :memo)
    edit_params  = store_params.merge(user_id: user.id)

    if store.present?
      store.update(edit_params)
    else
      store = Store.new(edit_params).save!
    end
    result = 'true'
  rescue => e
    p ">>>>>>>>>>> error! : #{e}"
    Rails.logger.error ">>>>>>>>>>> error! : #{e}"
    result = 'false'
  ensure
    render json: {result: result}
  end

  def get
    store = Store.find_by(id: params[:id])
    ret_data = store.attributes
  rescue => e
    p ">>>>>>>>>>> error! : #{e}"
    Rails.logger.error ">>>>>>>>>>> error! : #{e}"
    ret_data = {}
  ensure
    render json: { store: ret_data }
  end

  def search
    limit = rand(1..5)
    stores = Store.all.limit(limit)

    ret_data = []
    stores.each do |store|
      ret_hash = {}
      store.attributes.each do |k, v|
        ret_hash[k] = (v || '')
      end
      ret_data << ret_hash
    end

    render json: { stores: ret_data }
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < Api::ApiBaseController
  def register
    if User.find_by(user_id: params[:user_id])
      result  = 'false'
      message = "'#{params[:user_id]}' was already used ! Please chenge others..."
    else
      salt     = Digest::SHA1.hexdigest("salt-#{Time.now}")
      password = Digest::SHA1.hexdigest("#{salt}--#{params[:password]}--}")

      user_params = ActionController::Parameters.new(params).permit(:user_id, :user_type)

      user = User.new(user_params.merge({ password: password, salt: salt}))
      user.save!
      result = 'true'
    end
  rescue => e
    p ">>>>>>>>>>> error! : #{e}"
    Rails.logger.error ">>>>>>>>>>> error! : #{e}"
    result  = 'false'
    message = 'raise some error !'
  ensure
    render json: {result: result, message: message}
  end

  def login
    user = User.find_by(user_id: params[:user_id])
    if user.password == Digest::SHA1.hexdigest("#{user.salt}--#{params[:password]}--}")
      result = 'true'
      user_type = user.user_type
    else
      result = 'false'
    end
  rescue => e
    p ">>>>>>>>>>> error! : #{e}"
    Rails.logger.error ">>>>>>>>>>> error! : #{e}"
    result = 'false'
  ensure
    render json: {result: result, user_type: user_type}
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end
end

app/controllers/matchings_controller.rb
class MatchingsController < ApplicationController
  def index
    @matchings = Matching.all
  end

  def show
    @matching = Matching.find(params[:id])
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  def index
    @stores = Store.all
  end

  def show
    @store = Store.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/matchings_helper.rb
module MatchingsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :mail_address %><br>
    <%= f.text_field :mail_address %>
  </div>
  <div class="field">
    <%= f.label :memo %><br>
    <%= f.text_field :memo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<h1>Listing customers</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Name</th>
      <th>Mail address</th>
      <th>Memo</th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.id %> : <%= link_to customer.user_id, customer %></td>
        <td><%= customer.name %></td>
        <td><%= customer.mail_address %></td>
        <td><%= customer.memo %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/customers/new.html.erb
<h1>New customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @customer.user_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @customer.name %>
</p>

<p>
  <strong>Mail address:</strong>
  <%= @customer.mail_address %>
</p>

<p>
  <strong>Memo:</strong>
  <%= @customer.memo %>
</p>

<%= link_to 'Back', customers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MassageApi</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/matchings/_form.html.erb
<%= form_for(@matching) do |f| %>
  <% if @matching.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@matching.errors.count, "error") %> prohibited this matching from being saved:</h2>

      <ul>
      <% @matching.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :customer_id %><br>
    <%= f.number_field :customer_id %>
  </div>
  <div class="field">
    <%= f.label :store_id %><br>
    <%= f.number_field :store_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/matchings/edit.html.erb
<h1>Editing matching</h1>

<%= render 'form' %>

<%= link_to 'Show', @matching %> |
<%= link_to 'Back', matchings_path %>

app/views/matchings/index.html.erb
<h1>Listing matchings</h1>

<table>
  <thead>
    <tr>
      <th>Customer</th>
      <th>Store</th>
      <th>Enable</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @matchings.each do |matching| %>
      <tr>
        <td><%= matching.id %> : <%= matching.customer_id %></td>
        <td><%= matching.store_id %></td>
        <td><%= matching.enable_flg %></td>
        <td><%= link_to 'Show', matching %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/matchings/new.html.erb
<h1>New matching</h1>

<%= render 'form' %>

<%= link_to 'Back', matchings_path %>

app/views/matchings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer:</strong>
  <%= @matching.customer_id %>
</p>

<p>
  <strong>Store:</strong>
  <%= @matching.store_id %>
</p>

<%= link_to 'Back', matchings_path %>

app/views/stores/_form.html.erb
<%= form_for(@store) do |f| %>
  <% if @store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% @store.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :geo_data %><br>
    <%= f.text_field :geo_data %>
  </div>
  <div class="field">
    <%= f.label :mail_address %><br>
    <%= f.text_field :mail_address %>
  </div>
  <div class="field">
    <%= f.label :memo %><br>
    <%= f.text_field :memo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing store</h1>

<%= render 'form' %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

app/views/stores/index.html.erb
<h1>Listing stores</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Name</th>
      <th>Address</th>
      <th>Geo data</th>
      <th>Mail address</th>
      <th>Memo</th>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= store.id %> : <%= store.user_id %></td>
        <td><%= link_to store.name, store %></td>
        <td><%= store.address %></td>
        <td><%= store.geo_data %></td>
        <td><%= store.mail_address %></td>
        <td><%= store.memo %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/stores/new.html.erb
<h1>New store</h1>

<%= render 'form' %>

<%= link_to 'Back', stores_path %>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @store.user_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @store.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @store.address %>
</p>

<p>
  <strong>Geo data:</strong>
  <%= @store.geo_data %>
</p>

<p>
  <strong>Mail address:</strong>
  <%= @store.mail_address %>
</p>

<p>
  <strong>Memo:</strong>
  <%= @store.memo %>
</p>

<%= link_to 'Back', stores_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :user_type %><br>
    <%= f.text_field :user_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>User id</th>
      <th>Password</th>
      <th>User type</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %> : <%= link_to user.user_id, user %></td>
        <td><%= user.password %></td>
        <td><%= user.user_type %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User id:</strong>
  <%= @user.user_id %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>User type:</strong>
  <%= @user.user_type %>
</p>

<%= link_to 'Back', users_path %>